# fly.toml app configuration file generated for slvssb on 2023-08-29T00:00:11+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "slvssb"
primary_region = "bom"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
